export const ApplicationTimelineStatus = {
    PENDING: "PENDING",
    QUALIFIED: "QUALIFIED",
    REJECTED: "REJECTED",
    IN_PROGRESS: "IN_PROGRESS",
    VERDICT_PENDING: "VERDICT_PENDING",
    COMPLETED: "COMPLETED"
}